CREATE TABLE IF NOT EXISTS kullanicilar (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tam_ad VARCHAR(255) NOT NULL,
  fakulte VARCHAR(100) NOT NULL,
  fakulte_adi VARCHAR(255) NOT NULL,
  bolum VARCHAR(255) NOT NULL,
  sartlari_kabul TINYINT(1) NOT NULL DEFAULT 0,
  sozlesmeyi_kabul TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 